### ISSUE TITLE
PBL ID#37 - Verify whether all the components are developed as per the requirements

### ISSUE THREAD

**Issue by Chami-hbm** [Chami-hbm/Team-GNEXT#12]
- [x] Study the project specification and requirements in each stage deeply
- [x] Check and verify functional capabilities
- [x] Verify  the operational capabilities
- [x] Study and check verification and validation Processes
- [x] Verify all the components meets its testing requirements
- [x] Verify and finalized all the components are fulfilled their requirements

**Comment by Saku-SP** [comment]
Done
