### ISSUE TITLE
PBL ID#10 - As a Player I want to Play the game

### ISSUE THREAD

**Issue by Chami-hbm** [Chami-hbm/Team-GNEXT#14]
- [x] Monitor the performance of web services applications.
- [x] Verify the Simulator process is up and running
- [x] Design and implement Gameboard UI
- [ ] Connect the Service to the UI
- [ ] Sync all backend components - Player,broker,Analyst etc.
- [x] Desing the test methods for load and stress testing
- [ ] Testing to find bottlenecks and performance

**Comment by Saku-SP** [comment]
game board in progress

**Comment by Saku-SP** [comment]
moved to sprint 3

**Comment by Saku-SP** [comment]
Completed the PBL ID#10
