### ISSUE TITLE
PBL ID#15 - As an Analyst would like to Decide which shares to be buy or sell

### ISSUE THREAD

**Issue by Chami-hbm** [Chami-hbm/Team-GNEXT#15]
- [x] Discuss an analysis method to develop the scenario
- [x] Identify the components and build a design
- [x] Design the back-end process for multiple scenarios
- [x] Create Test Cases
- [x] Implement the solution & Unit testing Phase

**Comment by Saku-SP** [comment]
Completed the PBL ID#15
