### ISSUE TITLE
PBL ID#21 - As a PlayerAI I want to set the amount of money in hand of the player

### ISSUE THREAD

**Issue by Chami-hbm** [Chami-hbm/Team-GNEXT#19]
- [x] Review the requirement and identify the pre-conditions
- [x] Develop an algorithm to handle initial money transfer to players account when registration completed
- [x] Implement the data files and classes
- [x] Implement the methods
- [x] Verification & Validation 
- [x] Test the initial investment process for the Player

**Comment by Saku-SP** [comment]
Done
