### ISSUE TITLE
PBL ID#24 - As a Player I would be able to sell shares

### ISSUE THREAD

**Issue by Chami-hbm** [Chami-hbm/Team-GNEXT#22]
- [x] Storyboard a UI to capture SELL commands
- [x] Design a Service to handle the deposit request
- [x] Create Test Cases
- [x] Implement the Service
- [x] Implement the UI
- [x] Connect the Service to the UI

**Comment by Saku-SP** [comment]
Completed the PBL ID#24

**Comment by Saku-SP** [comment]
Done
