### ISSUE TITLE
PBL ID#27 - As a Broker I would be able to update share values

### ISSUE THREAD

**Issue by Chami-hbm** [Chami-hbm/Team-GNEXT#30]
- [x] Storyboard a UI to capture UPDATE commands
- [x] Design a Service to handle both shares adding/dropping requests
- [x] Create Test Cases
- [x] Implement the Service
- [x] Implement the UI
- [x] Connect the Service to the UI

**Comment by Saku-SP** [comment]
UI - in progress

**Comment by Saku-SP** [comment]
Done and tested
