### ISSUE TITLE
PBL ID#29 - As a Broker I want to View Stock Prices

### ISSUE THREAD

**Issue by Chami-hbm** [Chami-hbm/Team-GNEXT#32]
- [x] Storyboard a UI to view the price schedule
- [x] Design a Service to expose this information
- [x] Create Test Cases
- [x] Implement the Service
- [x] Implement the UI
- [x] Connect the Service to the UI

**Comment by Saku-SP** [comment]
Logic - done

**Comment by Saku-SP** [comment]
Done
