### ISSUE TITLE
PBL ID#30 - As a Broker I want to Deal with a player to Analyse Player's Portfolio

### ISSUE THREAD

**Issue by Chami-hbm** [Chami-hbm/Team-GNEXT#33]
- [x] Research how to handle the range of investment by a player
- [x] Design a method to capture amount of investment
- [x] Implement the design
- [x] Implement the methods
- [x] Create Test Cases
- [x] Test the ability to deal with the players portfolio

**Comment by Saku-SP** [comment]
Done
