### ISSUE TITLE
PBL ID#34 -  Functional and Full Smoke Testing

### ISSUE THREAD

**Issue by Chami-hbm** [Chami-hbm/Team-GNEXT#38]
- [x] Create a Smoke Test plan according to the project template
- [x] Documentation and maintenance of test cases
- [x] Create a test strategy
- [x] Test Execution based on the entire application
- [x] Verify and validate User Acceptance Scenarios
- [x] Prioritize the defects and assign to team

**Comment by Saku-SP** [comment]
Done
