### ISSUE TITLE
PBL ID#3 - Implement the web service and basic classes

### ISSUE THREAD

**Issue by Chami-hbm** [Chami-hbm/Team-GNEXT#4]
- [x] Review all the components of web services to learn how we can make our Web services
- [x] Develop web services applications
- [x] Assemble web services.
- [x] Deploy Web services.
- [x] Publish the service
- [x] Monitor the performance of web services applications.
- [x] Troubleshoot web services.

**Comment by Saku-SP** [comment]
completed the web service and basic classes
