### ISSUE TITLE
PBL ID#36 - Regression and UAT testing

### ISSUE THREAD

**Issue by Chami-hbm** [Chami-hbm/Team-GNEXT#40]
- [x] Identify the newly introduced changeset
- [x] Ensure the stability of the existing functionality with new changes
- [x] UAT testing phase with fully developed application
- [x] Check the requirements available according to the acceptance criteria
- [x] Verify all the requirements and defects reporting
- [x] Finalize the project with resolved defects

**Comment by Saku-SP** [comment]
identified 10 bugs and those are fixed. Tasks Done
