### ISSUE TITLE
PBL ID#8 - Implement the Random Trends Stock Market Model 

### ISSUE THREAD

**Issue by Chami-hbm** [Chami-hbm/Team-GNEXT#42]
- [x] Research about Trends Stock Market Model
- [x] Study of the other stock market trending behavior and  related applications
- [x] Analyse the model as per our requirements
- [x] Identify the impacted parameters
- [x] Desing the algorithm and classes
- [x] Design the test methods

**Comment by Saku-SP** [comment]
designing Done. Trends Stock Market Model implementation is in progress now

**Comment by Saku-SP** [comment]
moved to Sprint 3

**Comment by Saku-SP** [comment]
Completed the PBL ID#8
